---
deployment:
  tasks:
    # Always reset to the latest remote version of deploy
    - cd /home/foggyhex/repositories/foggy-hex && /usr/local/cpanel/3rdparty/bin/git fetch origin deploy && /usr/local/cpanel/3rdparty/bin/git reset --hard origin/deploy

    # Define the public folder where your site lives
    - export DEPLOYPATH=/home/foggyhex/public_html/

    # Copy build files into public_html
    - /bin/rsync -a --delete ./ $DEPLOYPATH
