// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 25/9/2025, 18:59:39
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/jorgepaez/sites/foggy-hex/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jorgepaez/sites/foggy-hex/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jorgepaez/sites/foggy-hex/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jorgepaez/sites/foggy-hex/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jorgepaez/sites/foggy-hex/app/plugins/**/*.{js,ts,mjs}","/Users/jorgepaez/sites/foggy-hex/app/composables/**/*.{js,ts,mjs}","/Users/jorgepaez/sites/foggy-hex/app/utils/**/*.{js,ts,mjs}","/Users/jorgepaez/sites/foggy-hex/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jorgepaez/sites/foggy-hex/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/jorgepaez/sites/foggy-hex/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/jorgepaez/sites/foggy-hex/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;