// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 19/9/2025, 17:45:47
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Users/jorgepaez/sites/foggy/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jorgepaez/sites/foggy/app/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jorgepaez/sites/foggy/app/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jorgepaez/sites/foggy/app/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jorgepaez/sites/foggy/app/plugins/**/*.{js,ts,mjs}","/Users/jorgepaez/sites/foggy/app/composables/**/*.{js,ts,mjs}","/Users/jorgepaez/sites/foggy/app/utils/**/*.{js,ts,mjs}","/Users/jorgepaez/sites/foggy/app/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Users/jorgepaez/sites/foggy/app/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Users/jorgepaez/sites/foggy/app/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Users/jorgepaez/sites/foggy/app/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;