import type { PageCollectionItemBase, DataCollectionItemBase } from '@nuxt/content'

declare module '@nuxt/content' {
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface FutureCollectionItem extends DataCollectionItemBase {
    slug: string;
    title: string;
    date: string;
    venue: string;
    image: string;
  }
  
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface PastCollectionItem extends DataCollectionItemBase {
    title: string;
    date: string;
    venue: string;
    image: string;
  }
  
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface ShowsCollectionItem extends DataCollectionItemBase {
    slug: string;
    title: string;
    date: string;
    time: string;
    venue: string;
    ticketUrl?: string;
    bands: {
    name: string;
    image: string;
    bandcamp?: string;
    description: string;
    }[];
  }
  

  interface PageCollections {
  }

  interface Collections {
    future: FutureCollectionItem
    past: PastCollectionItem
    shows: ShowsCollectionItem
  }
}
